name: Deploy Dev
on:
  push:
    branches:
      - main

env:
  DEPLOY_ENV: dev
  
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Tag Name
        id: set_tag_name
        run: echo "v1.${{ github.run_number }}" >> tag_name.txt

      - name: Create Tag
        run: |
          TAG_NAME=$(cat tag_name.txt)
          echo "Creating tag $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install NPM dependencies
      run: npm ci --cache .npm --prefer-offline
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build
      run: |
       NODE_OPTIONS=--max_old_space_size=4092
       npm run build
    - name: Deploy
      run: |
       sls deploy --stage ${{ env.DEPLOY_ENV }} --verbose --force
       sls plugin install -n serverless-prune-plugin
       sls prune --stage $DEPLOY_ENV -n 5 
